# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)

1.19.2


#### 3. Create a null vector of size 10

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [6]:
a=np.ones(8)
a.size

8

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [15]:
a=np.arange(30)
a=a[::-1]
a

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [20]:
a=np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [23]:
np.random.rand(3,3,3)

array([[[0.88446055, 0.48472497, 0.53699745],
        [0.62445848, 0.19778741, 0.46415916],
        [0.66177325, 0.29691686, 0.38027155]],

       [[0.09043133, 0.83333241, 0.21906476],
        [0.95054294, 0.80550758, 0.70447249],
        [0.79860663, 0.12970192, 0.75608218]],

       [[0.84422819, 0.60031779, 0.16493824],
        [0.44784696, 0.56584592, 0.80465761],
        [0.08009826, 0.98432758, 0.57639151]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
a=np.random.rand(10,10)
a,b=np.min(a),np.max(a)
a,b

(0.003987506044279332, 0.9872560919269412)

#### 14. Create a random vector of size 30 and find the mean value

In [25]:
a=np.random.rand(30)
np.mean(a)

0.4508524112440963

#### 15. Create a 2d array with 1 on the border and 0 inside

In [27]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
a=np.arange(25).reshape(5,5)
np.pad(a,(1,1),"constant",constant_values=(1,1))

array([[ 1,  1,  1,  1,  1,  1,  1],
       [ 1,  0,  1,  2,  3,  4,  1],
       [ 1,  5,  6,  7,  8,  9,  1],
       [ 1, 10, 11, 12, 13, 14,  1],
       [ 1, 15, 16, 17, 18, 19,  1],
       [ 1, 20, 21, 22, 23, 24,  1],
       [ 1,  1,  1,  1,  1,  1,  1]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [45]:
a=np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if(i-1==j):
            a[i][j]=i
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [46]:
a=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if((i+j)%2==0):
            a[i][j]=1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?